### ISSUE TITLE
More immediate reaction to large jumps in clock time

### ISSUE THREAD

**Issue by wlhlm** [amir/sctd#3]
Currently, sctd's main loop runs in 300s intervals (using `thread::sleep`). This can result in jarring behavior when the time changes in big steps requiring adjustments to the color temperature set by sctd. It can leave the display on the wrong color temperature for almost 5 minutes, should such a jump occur right after sctd checks the time. For example, time jumps may be triggered by ntpd, or resuming from hibernation (such as hibernating the system in the evening and resuming in the morning). The problem is most noticeable in the latter case.

I think lowering the check interval to something like 30s improves this situation while not noticeably increasing resource usage.

**Comment by amir** [comment]
Thanks for reporting this. I'll make the sleep interval configurable.

**Comment by wlhlm** [comment]
Thanks for considering this! Though, I'm struggling to understand why this would need to be configurable rather than just choosing a smaller interval. The algorithm only depends on the time of day and not on the check interval. Querying the system for the current time is rather cheap (so just decreasing interval length shouldn't have a noticeable impact). Adding a config option unnecessarily inflates sctd's user interface contrary to its simple nature.

As an alternative, I suggest setting the interval to a flat out lower value, something like 10 or 15 seconds (redshift uses [5 seconds](https://github.com/jonls/redshift/blob/490ba2aae9cfee097a88b6e2be98aeb1ce990050/src/redshift.c#L126)) and change the main loop logic to only call `sctd::set_temp()` when the target temperature value changed from the old value.

**Comment by amir** [comment]
You're absolutely right! I reduced the sleep time to 5 seconds and will only attempt to change the temperature if the value is changed. I also took the opportunity to add a proper release process. There will now be tarballs in releases whenever a new version is tagged.

**Comment by wlhlm** [comment]
Works like a charm. Thanks.

I've uploaded a package to the [AUR](https://aur.archlinux.org/packages/sctd/).

**Comment by amir** [comment]
Thanks very much! I should update the README then.
